# Code generated by protoc-gen-twirp_ruby 1.0.0, DO NOT EDIT.
require 'twirp'
require_relative 'service_pb.rb'

module Courier
  class TranslatorService < Twirp::Service
    package 'courier'
    service 'Translator'
    rpc :Translate, TranslateRequest, TranslatedTweetList, :ruby_method => :translate
  end

  class TranslatorClient < Twirp::Client
    client_for TranslatorService
  end
end
